package com.chinagpay.boss.common.vo;

import java.io.Serializable;

public class BankBehalfMerConfig  implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 2843165911995767798L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.MER_ID
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private Long merId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.BALANCE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private Long balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.FEE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private Integer fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.AVAILABLE_BALANCE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private Long availableBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.BLOCKED_BALANCES
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private Long blockedBalances;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.AVAILABLE_FEE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private Integer availableFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.BLOCKED_FEE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private Integer blockedFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.RATE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private Integer rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.STATUS
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.CREATE_TIME
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.FINISH_TIME
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private String finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.BACK_URL
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private String backUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.MER_NAME
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private String merName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.MER_SYS_ID
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private String merSysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.MER_TYPE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private Byte merType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.TRANS_MER_ID
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private String transMerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.BANKID
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private Long bankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.GW_TYPE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private String gwType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.BIZ_TYPE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private Byte bizType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.START_TIME
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.END_TIME
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.VERSION
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.KEY_STR
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private String keyStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.FIELD_2
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private String field2;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.PUBLIC_KEY
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private String publicKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANK_BEHALF_MER_CONFIG.FIELD_1
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    private String field1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.PUBLIC_KEY
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.PUBLIC_KEY
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public String getPublicKey() {
        return publicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.PUBLIC_KEY
     *
     * @param publicKey the value for BANK_BEHALF_MER_CONFIG.PUBLIC_KEY
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.FIELD_1
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.FIELD_1
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.FIELD_1
     *
     * @param field1 the value for BANK_BEHALF_MER_CONFIG.FIELD_1
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setField1(String field1) {
        this.field1 = field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.MER_ID
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.MER_ID
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public Long getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.MER_ID
     *
     * @param merId the value for BANK_BEHALF_MER_CONFIG.MER_ID
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setMerId(Long merId) {
        this.merId = merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.BALANCE
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.BALANCE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public Long getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.BALANCE
     *
     * @param balance the value for BANK_BEHALF_MER_CONFIG.BALANCE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setBalance(Long balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.FEE
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.FEE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public Integer getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.FEE
     *
     * @param fee the value for BANK_BEHALF_MER_CONFIG.FEE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setFee(Integer fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.AVAILABLE_BALANCE
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.AVAILABLE_BALANCE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public Long getAvailableBalance() {
        return availableBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.AVAILABLE_BALANCE
     *
     * @param availableBalance the value for BANK_BEHALF_MER_CONFIG.AVAILABLE_BALANCE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setAvailableBalance(Long availableBalance) {
        this.availableBalance = availableBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.BLOCKED_BALANCES
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.BLOCKED_BALANCES
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public Long getBlockedBalances() {
        return blockedBalances;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.BLOCKED_BALANCES
     *
     * @param blockedBalances the value for BANK_BEHALF_MER_CONFIG.BLOCKED_BALANCES
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setBlockedBalances(Long blockedBalances) {
        this.blockedBalances = blockedBalances;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.AVAILABLE_FEE
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.AVAILABLE_FEE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public Integer getAvailableFee() {
        return availableFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.AVAILABLE_FEE
     *
     * @param availableFee the value for BANK_BEHALF_MER_CONFIG.AVAILABLE_FEE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setAvailableFee(Integer availableFee) {
        this.availableFee = availableFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.BLOCKED_FEE
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.BLOCKED_FEE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public Integer getBlockedFee() {
        return blockedFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.BLOCKED_FEE
     *
     * @param blockedFee the value for BANK_BEHALF_MER_CONFIG.BLOCKED_FEE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setBlockedFee(Integer blockedFee) {
        this.blockedFee = blockedFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.RATE
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.RATE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public Integer getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.RATE
     *
     * @param rate the value for BANK_BEHALF_MER_CONFIG.RATE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setRate(Integer rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.STATUS
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.STATUS
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.STATUS
     *
     * @param status the value for BANK_BEHALF_MER_CONFIG.STATUS
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.CREATE_TIME
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.CREATE_TIME
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.CREATE_TIME
     *
     * @param createTime the value for BANK_BEHALF_MER_CONFIG.CREATE_TIME
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.FINISH_TIME
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.FINISH_TIME
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public String getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.FINISH_TIME
     *
     * @param finishTime the value for BANK_BEHALF_MER_CONFIG.FINISH_TIME
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setFinishTime(String finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.BACK_URL
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.BACK_URL
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public String getBackUrl() {
        return backUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.BACK_URL
     *
     * @param backUrl the value for BANK_BEHALF_MER_CONFIG.BACK_URL
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setBackUrl(String backUrl) {
        this.backUrl = backUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.MER_NAME
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.MER_NAME
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public String getMerName() {
        return merName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.MER_NAME
     *
     * @param merName the value for BANK_BEHALF_MER_CONFIG.MER_NAME
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setMerName(String merName) {
        this.merName = merName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.MER_SYS_ID
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.MER_SYS_ID
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public String getMerSysId() {
        return merSysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.MER_SYS_ID
     *
     * @param merSysId the value for BANK_BEHALF_MER_CONFIG.MER_SYS_ID
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setMerSysId(String merSysId) {
        this.merSysId = merSysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.MER_TYPE
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.MER_TYPE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public Byte getMerType() {
        return merType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.MER_TYPE
     *
     * @param merType the value for BANK_BEHALF_MER_CONFIG.MER_TYPE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setMerType(Byte merType) {
        this.merType = merType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.TRANS_MER_ID
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.TRANS_MER_ID
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public String getTransMerId() {
        return transMerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.TRANS_MER_ID
     *
     * @param transMerId the value for BANK_BEHALF_MER_CONFIG.TRANS_MER_ID
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setTransMerId(String transMerId) {
        this.transMerId = transMerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.BANKID
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.BANKID
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public Long getBankid() {
        return bankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.BANKID
     *
     * @param bankid the value for BANK_BEHALF_MER_CONFIG.BANKID
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setBankid(Long bankid) {
        this.bankid = bankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.GW_TYPE
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.GW_TYPE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public String getGwType() {
        return gwType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.GW_TYPE
     *
     * @param gwType the value for BANK_BEHALF_MER_CONFIG.GW_TYPE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setGwType(String gwType) {
        this.gwType = gwType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.BIZ_TYPE
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.BIZ_TYPE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public Byte getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.BIZ_TYPE
     *
     * @param bizType the value for BANK_BEHALF_MER_CONFIG.BIZ_TYPE
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setBizType(Byte bizType) {
        this.bizType = bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.START_TIME
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.START_TIME
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.START_TIME
     *
     * @param startTime the value for BANK_BEHALF_MER_CONFIG.START_TIME
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.END_TIME
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.END_TIME
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.END_TIME
     *
     * @param endTime the value for BANK_BEHALF_MER_CONFIG.END_TIME
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.VERSION
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.VERSION
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.VERSION
     *
     * @param version the value for BANK_BEHALF_MER_CONFIG.VERSION
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.KEY_STR
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.KEY_STR
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public String getKeyStr() {
        return keyStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.KEY_STR
     *
     * @param keyStr the value for BANK_BEHALF_MER_CONFIG.KEY_STR
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setKeyStr(String keyStr) {
        this.keyStr = keyStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANK_BEHALF_MER_CONFIG.FIELD_2
     *
     * @return the value of BANK_BEHALF_MER_CONFIG.FIELD_2
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANK_BEHALF_MER_CONFIG.FIELD_2
     *
     * @param field2 the value for BANK_BEHALF_MER_CONFIG.FIELD_2
     *
     * @mbggenerated Thu Aug 20 15:08:03 CST 2015
     */
    public void setField2(String field2) {
        this.field2 = field2;
    }
}