package com.chinagpay.boss.common.bean;

/**
 * Created by hanbinyu on 2016/7/18.
 */
public enum CurrencyEnum {
	X("未知的",2),
    AED("阿联酋迪拉姆", 2),
    ALL("阿尔巴尼亚列克", 2),
    ANG("列斯荷兰盾", 2),
    AOA("安哥拉宽扎",2),
    ARS("阿根廷比索", 2),
    ATS("奥地利先令", 2),
    AUD("澳元", 2),
    AWG("阿鲁巴岛弗罗林", 2),
    BBD("巴巴多斯元", 2),
    BAM("波黑马克",2),
    BDT("孟加拉塔卡", 2),
    BGN("保加利亚列瓦", 2),
    BHD("巴林第纳尔", 2),
    BIF("布隆迪法郎", 2),
    BMD("百慕大元", 2),
    BND("文莱元", 2),
    BOB("玻利维亚诺", 2),
    BRL("巴西里亚伊", 2),
    BSD("巴哈马元", 2),
    BTN("不丹卢比", 2),
    BWP("博茨瓦纳普拉", 2),
    BYR("白俄罗斯卢布", 2),
    BZD("伯利兹元", 2),
    CAD("加拿大元", 2),
    CHF("瑞士法郎", 2),
    CLP("智利比索", 2),
    CNY("人民币", 2),
    COP("哥伦比亚比索", 2),
    CRC("哥斯达黎加科朗", 2),
    CUP("古巴比索", 2),
    CVE("佛得角埃斯库多", 2),
    CZK("捷克克朗", 2),
    DEM("德国马克", 2),
    DJF("吉布提法郎", 2),
    DKK("丹麦克朗", 2),
    DOP("多米尼加比索", 2),
    DZD("阿尔及利亚第纳尔", 2),
    ECS("苏克雷", 2),
    EGP("埃及镑", 2),
    ETB("埃塞俄比亚比尔", 2),
    ESP("比塞塔", 2),
    EUR("欧元", 2),
    FIM("芬兰马克", 2),
    FJD("斐济元", 2),
    FKP("福克兰群岛镑", 2),
    FRF("法国法郎", 2),
    GBP("英镑", 2),
    GIP("直布罗陀镑", 2),
    GMD("冈比亚达拉西", 2),
    GNF("几内亚法郎", 2),
    GTQ("危地马拉格查尔", 2),
    GYD("圭亚那元", 2),
    HKD("港元", 2),
    HNL("洪都拉斯伦皮拉", 2),
    HRK("克罗地亚库纳", 2),
    HTG("海地古德", 2),
    HUF("匈牙利福林", 2),
    IDR("印度尼西亚卢比(盾)", 2),
    ILS("以色列镑", 2),
    INR("印度卢比", 2),
    IQD("伊拉克第纳尔", 2),
    IRR("伊朗里亚尔", 2),
    ISK("冰岛克朗", 2),
    JMD("牙买加元", 2),
    JOD("约旦第纳尔", 2),
    JPY("日元", 2),
    KES("肯尼亚先令", 2),
    KHR("柬埔寨利尔斯", 2),
    KMF("科摩罗法郎", 2),
    KPW("朝鲜圆", 2),
    KRW("韩元", 2),
    KWD("科威特第纳尔", 2),
    KZT("哈萨克斯坦腾格", 2),
    LAK("老挝基普", 2),
    LBP("黎巴嫩镑", 2),
    LKR("斯里兰卡卢比", 2),
    LRD("利比里亚元", 2),
    LSL("莱索托洛提", 2),
    LTL("立陶宛里塔斯", 2),
    LVL("拉脱维亚拉图", 2),
    LYD("利比亚第纳尔", 2),
    MAD("摩洛哥道拉姆", 2),
    MDL("摩尔多瓦列伊", 2),
    MKD("马其顿第纳尔", 2),
    MMK("缅甸元", 2),
    MNT("蒙古图格里克", 2),
    MOP("澳门元", 2),
    MRO("毛里塔尼亚乌吉亚", 2),
    MUR("毛里求斯卢比", 2),
    MVR("马尔代夫卢非亚", 2),
    MWK("马拉维克瓦查", 2),
    MXN("墨西哥比索", 2),
    MYR("马来西亚林吉特", 2),
    NAD("纳米比亚元", 2),
    NGN("尼日利亚奈拉", 2),
    NIO("尼加拉瓜科多巴", 2),
    NOK("挪威克朗", 2),
    NPR("尼泊尔卢比", 2),
    NZD("新西兰元", 2),
    OMR("阿曼里亚尔", 2),
    PAB("巴拿马巴尔博亚", 2),
    PEN("秘鲁索尔", 2),
    PGK("巴布亚新几内亚基那", 2),
    PHP("菲律宾比索", 2),
    PKR("巴基斯坦卢比", 2),
    PLN("波兰兹罗提", 2),
    PYG("巴拉圭瓜拉尼", 2),
    QAR("卡塔尔利尔", 2),
    RON("罗马尼亚新列伊", 2),
    RUB("俄罗斯卢布", 2),
    RWF("卢旺达法郎", 2),
    SAR("沙特阿拉伯里亚尔", 2),
    SBD("所罗门群岛元", 2),
    SCR("塞舌尔法郎", 2),
    SEK("瑞典克朗", 2),
    SGD("新加坡元", 2),
    SHP("圣赫勒拿群岛磅", 2),
    SLL("塞拉利昂利昂", 2),
    SOS("索马里先令", 2),
    STD("圣多美多布拉", 2),
    SVC("萨尔瓦多科朗", 2),
    SYP("叙利亚镑", 2),
    SZL("斯威士兰里兰吉尼", 2),
    THB("泰国铢", 2),
    TND("突尼斯第纳尔", 2),
    TOP("汤加潘加", 2),
    TRY("土耳其新里拉", 2),
    TTD("特立尼达和多巴哥元", 2),
    TWD("台币", 2),
    TZS("坦桑尼亚先令", 2),
    UAH("乌克兰赫夫米", 2),
    USD("美元", 2),
    UYU("乌拉圭新比索", 2),
    VND("越南盾", 2),
    VUV("瓦努阿图瓦图", 2),
    WST("萨摩亚塔拉", 2),
    XAF("刚果中非共同体法郎", 2),
    XAG("银价盎司", 2),
    XAU("金价盎司", 2),
    XCD("格林纳达东加勒比元", 2),
    XCP("铜价盎司", 2),
    XOF("多哥非洲共同体法郎", 2),
    XPD("钯价盎司", 2),
    XPF("太平洋法郎", 2),
    XPT("铂价盎司", 2),
    YER("也门里亚尔", 2),
    ZAR("南非兰特", 2),
    ZMK("赞比亚克瓦查", 2),
    ZRZ("扎伊尔", 2),
    ZWD("津巴布韦元", 2),
    VEF("委内瑞拉博利瓦",2),
    UZS("乌兹别克斯坦苏姆",2),
    UGX("乌干达先令",2),
    SSP("南苏丹镑",2),
    SDG("新苏丹镑",2),
    RSD("塞尔维亚第纳尔",2),
    GHS("加纳塞地",2),
    SRD("苏里南元",2),
    SDR("特别提款权",2),
	ZMW("赞比亚克瓦查",2);
    private String unit;
    private int accuracy;

    private CurrencyEnum(String unit, int accuracy) {
        this.unit = unit;
        this.accuracy = accuracy;
    }

    public String getUnit() {
        return this.unit;
    }

    public int getAccuracy() {
        return this.accuracy;
    }
    public static String getCyName(String cyCode){
    	try{
    		return CurrencyEnum.valueOf(cyCode).getUnit();
    	}catch(Exception e){
    		return cyCode;
    	}
	}
    public static void main(String[] args) {
		System.out.println(CurrencyEnum.ALL.getCyName("CNY"));
	}
}
